resources:
  repositories:
  - repository: templates
    type: git
    name: templates

trigger:

variables:
- name: service_connection_name
  value: hard-coded
- name: backend_service_connection_name
  value: hard-coded
- name: env
  value: dev
- name: infraenv
  value: nonprod
- name: app
  value: test
- name: app_service_plan_name
  value: demo-plan-dev
- name: app_service_plan_resource_group
  value: demo-rg
- name: virtual_network_name
  value: dev-vnet
- name: virtual_networks_resource_group_name
  value: dev-network-rg
- name: subnet_name
  value: app-subnet
- name: docker_image_name
  value: something:latest
- name: docker_registry_url
  value: acr.azurecr.io
- name: tags
  value: {}

stages:
- template: appsvcapp-template.yml@templates